### ISSUE TITLE
The random Tic-Tac-Toe index is used incorrectly

### ISSUE THREAD

**Issue by dhermes** [x1ddos/go-tictactoe#2]
In
https://github.com/crhym3/go-tictactoe/blob/82ea36f39cea14fc749fada334c9edf202b21b82/tictactoe/api.go#L70
we use

```
randomIdx := r.Intn(freeIdxLen)
runes[randomIdx] = 'O'
```

but this `randomIdx` is an index in the list of `freeIndices` so we first need to find our index and then replace it:

```
runes[freeIndices[randomIdx]] = 'O'
```

**Comment by x1ddos** [comment]
Haha. Nice catch! It seems I haven't played enought.
